//! The OpenAPI document, served as Swagger UI at `/docs`.
//!
//! Generated from the same annotations that sit on the handlers, so the
//! documentation cannot drift from the implementation — a route that changes
//! shape without updating its annotation fails to compile.

use utoipa::openapi::security::{Http, HttpAuthScheme, SecurityScheme};
use utoipa::{Modify, OpenApi};

use crate::error::{ErrorDetail, ErrorResponse};
use crate::routes::dto::*;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "NigChat API",
        version = "1.0.0",
        description = "\
Unified backend for every NigChat client — iOS, iPadOS, Android, Android \
tablet, Web, Windows, macOS and Linux. Clients never connect to the database; \
everything goes through these versioned endpoints and the authenticated \
WebSocket.

## Three things to get right

**1. Always send `client_message_id`.** Generate a UUID on the device *before* \
POSTing a message. Retrying with the same value returns the original message \
instead of creating a duplicate — this is what makes a send safe to retry on a \
dropped connection.

**2. Order and paginate by `seq`, never `created_at`.** `seq` is a \
per-conversation counter that only increases. Timestamps come from whichever \
server handled the write and will occasionally disagree. Store the highest \
`seq` you hold per conversation; that value is your sync cursor and your read \
receipt.

**3. The socket is a fast path, not the source of truth.** A dropped socket \
must never mean a lost message. On reconnect, `GET /v1/conversations`, compare \
each `head_seq` with your local cursor, and pull any gap with \
`?after_seq=`. Build this on day one.

## Encryption

Message bodies are ciphertext produced on the device (base64 in JSON). The \
server orders and routes; it cannot read. Consequences: search runs on-device, \
push notifications carry no message text, and link previews are generated by \
the sender.

## Errors

Every error is `{\"error\": {\"code\", \"message\"}}`. **Branch on `code`, \
never on `message`** — messages are for humans and may be reworded.
",
        contact(name = "NigChat Engineering"),
    ),
    servers(
        (url = "http://localhost:8080", description = "Local development"),
        (url = "https://api.nigchat.com", description = "Production"),
    ),
    paths(
        crate::routes::health::healthz,
        crate::routes::health::readyz,
        crate::routes::auth::request_otp,
        crate::routes::auth::verify_otp,
        crate::routes::auth::refresh,
        crate::routes::auth::logout,
        crate::routes::users::me,
        crate::routes::users::update_me,
        crate::routes::users::get_user,
        crate::routes::users::sync_contacts,
        crate::routes::users::block,
        crate::routes::users::unblock,
        crate::routes::users::list_devices,
        crate::routes::users::revoke_device,
        crate::routes::users::register_push_token,
        crate::routes::users::security_events,
        crate::routes::users::set_two_step_pin,
        crate::routes::users::disable_two_step,
        crate::routes::users::verify_two_step,
        crate::routes::users::get_by_username,
        crate::routes::conversations::list,
        crate::routes::conversations::create_direct,
        crate::routes::conversations::create_group,
        crate::routes::conversations::get,
        crate::routes::conversations::add_members,
        crate::routes::conversations::remove_member,
        crate::routes::conversations::set_role,
        crate::routes::conversations::mute,
        crate::routes::conversations::mark_delivered,
        crate::routes::conversations::mark_read,
        crate::routes::messages::send,
        crate::routes::messages::list,
        crate::routes::messages::edit,
        crate::routes::messages::delete,
        crate::routes::messages::react,
        crate::routes::notifications::list_tones,
        crate::routes::notifications::get_preferences,
        crate::routes::notifications::update_preferences,
        crate::routes::notifications::get_conversation_settings,
        crate::routes::notifications::update_conversation_settings,
        crate::routes::keys::publish,
        crate::routes::keys::bundles,
        crate::routes::keys::count,
    ),
    components(schemas(
        ErrorResponse, ErrorDetail, OkResponse, SeqResponse,
        RequestOtpRequest, RequestOtpResponse, VerifyOtpRequest, RefreshRequest,
        TokenPairResponse,
        MeResponse, PublicUserResponse, UpdateProfileRequest, ContactSyncRequest, BlockRequest, SetTwoStepPinRequest, VerifyPinRequest,
        DeviceResponse, RegisterPushTokenRequest,
        ConversationResponse, ConversationSummaryResponse, CreateDirectRequest,
        CreateGroupRequest, AddMembersRequest, SetRoleRequest, MuteRequest, MarkReadRequest, MarkDeliveredRequest,
        MessageResponse, SendMessageRequest, EditMessageRequest, ReactionRequest, MessagePage,
        NotificationToneResponse, NotificationPreferencesResponse, QuietHoursDto,
        UpdateNotificationPreferencesRequest, ConversationNotificationResponse,
        UpdateConversationNotificationsRequest,
        PublishKeysRequest, OneTimePreKeyDto, PreKeyBundleResponse, PreKeyCountResponse,
        SecurityEventResponse,
    )),
    modifiers(&BearerAuth),
    tags(
        (name = "auth", description = "Registration, sign-in and session lifecycle"),
        (name = "users", description = "Profile, contact discovery and blocking"),
        (name = "devices", description = "Linked devices"),
        (name = "conversations", description = "Direct chats, groups and channels"),
        (name = "messages", description = "Sending, reading, editing, reactions"),
        (name = "notifications", description = "Push tokens, tones, quiet hours, per-chat overrides"),
        (name = "encryption", description = "End-to-end encryption key directory"),
        (name = "security", description = "Security timeline"),
        (name = "system", description = "Health and readiness"),
    ),
)]
pub struct ApiDoc;

struct BearerAuth;

impl Modify for BearerAuth {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer",
                SecurityScheme::Http(
                    Http::builder()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .description(Some(
                            "Access token from /v1/auth/verify-otp. Valid for 15 minutes; \
                             refresh on a 401 with code `unauthorized` and retry once.",
                        ))
                        .build(),
                ),
            );
        }
    }
}
